### PR TITLE
Lemma updates

### PR DESCRIPTION
**Pull request by AngledLuffa**
I worked on a few lemma updates which have been discussed here or elsewhere:

lowercase pronoun i -> I in the lemma
lowercase month & day names -> Saturday in the lemma
numbers with , -> no comma in the lemma

### CODE REVIEW

**Comment by nschneid** [comment]
LGTM. I suppose one could have a feature explaining the capitalization difference (e.g. `Downcased=Yes`) but it's probably not necessary.

**Comment by nschneid** [comment]
Would you mind running the following script (I call it build.py) to update the source documents?

```py
#!/usr/bin/env python3
"""
Regenerate en_ewt-ud-{train,dev,test}.conllu from source files in the
not-to-release/sources directory.

Requires python3.6+
"""
FLIST_BASE_PATH = 'not-to-release/file-lists/files'
for split in ('train', 'dev', 'test'):
    flist = FLIST_BASE_PATH + '.' + split
    with open(flist, encoding='utf-8') as inF:
        fpaths = inF.readlines()
    with open(f'en_ewt-ud-{split}.conllu', 'w', encoding='utf-8') as outF:
        for fpath in fpaths:
            fpath = fpath.strip()
            with open('not-to-release/sources/' + fpath, encoding='utf-8') as inF:
                data = inF.read()
            outF.write(data)
```

**Comment by AngledLuffa** [comment]
This is going the wrong way, I think.  Do you have a script which takes
edits made directly to the en_ewt-ud-{train,dev,test}.conllu files and
distributes them to the source files?

**Comment by nschneid** [comment]
Oh good point, we want update_ewt_docs.py:

```py
#!/usr/bin/env python3
"""
Given a .conllu file with parses from multiple documents,
update individual document files under not-to-release/sources/
(e.g. reviews/001325.xml.conllu).

@author: Nathan Schneider (@nschneid)
@since: 2020-03-01

Requires python3.6+
"""
import sys, fileinput

SOURCES_PATH = 'not-to-release/sources'
outF = None

for ln in fileinput.input():
    if ln.startswith('# newdoc id = '):
        if outF:
            outF.close()
        fulldocid = ln[len('# newdoc id = '):].strip()
        subcorp, docid = fulldocid.split('-')
        filename = f'{SOURCES_PATH}/{subcorp}/{docid}.xml.conllu'
        #print(filename, file=sys.stderr)
        outF = open(filename, 'w', encoding='utf-8')
    elif ln.startswith('# streusle_sent_id') or ln.startswith('# mwe ='):
        continue    # STREUSLE-specific metadata lines
    outF.write(ln)
if outF: outF.close()
```

**Comment by AngledLuffa** [comment]
Alright, I distributed the changes.  Thanks for the tools to make it easier.

**Comment by AngledLuffa** [comment]
BTW I squashed the distributed updates with the updates to the en_ewt
files, in case the git history looks surprising.

**Pull request merged**
