### PR TITLE
added missing Person and Number (take 2)

### PR DESCRIPTION
**Pull request by lapalme**
A script was used to add missing Person and Number to verbs at indicative mood by following their subject links.
This fixed most cases, the remaining ones (a couple of hundreds) were corrected manually.
This exercise revealed a few bad "head" links that were also fixed.

### CODE REVIEW

**Comment by nschneid** [comment]
This is the master branch. We need it to be the dev branch.

**Comment by lapalme** [comment]
This the third time that I try to fork the dev branch .

I am now totally lost, because as soon as I try to do a single change, I am told to "resolve conflicts"... (I am using the Mac GUI for GitHub)
How should I start ?

screenshot

**Comment by nschneid** [comment]
Not familiar with the Mac GUI. Maybe you need to clone into a fresh directory? If you prefer to send me the script I can run it on the latest dev branch.

**Comment by lapalme** [comment]
Here is the Python3 script, but it creates a new file with a "NoSubject" attribute in the MISC field when the program cannot determine the Person and Number, so that these lines must be checked by hand afterwards...

What  command lines do you usually use to clone the the "right" dev directory and then to send updates ?
sorry for this trouble

[fixVerbNumberPerson.py.txt](https://github.com/UniversalDependencies/UD_English-EWT/files/6657880/fixVerbNumberPerson.py.txt)

**Comment by nschneid** [comment]
Following https://stackoverflow.com/a/9646323 I've managed to reset your fork at https://github.com/lapalme/UD_English-EWT/tree/dev to match the official dev branch. You should be able to apply your changes there.

**Comment by nschneid** [comment]
See #184

**Pull request closed without merging**
