### PR TITLE
Fractions

### PR DESCRIPTION
**Pull request by AngledLuffa**
I'm not 100% sure how to handle `sixth`, which is used as sixth place, not 1/6.  `third` in a similar context is labeled ADJ in the train set

```
# sent_id = weblog-juancole.com_juancole_20051126063000_ENG_20051126_063000-0006
# text = The third was being run by the head of an investment firm.
1       The     the     DET     DT      Definite=Def|PronType=Art       2       det     2:det   _
2       third   third   ADJ     JJ      Degree=Pos|NumType=Ord  5       nsubj:pass      5:nsubj:pass    _
3       was     be      AUX     VBD     Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin   5       aux     5:aux   _
4       being   be      AUX     VBG     VerbForm=Ger    5       aux:pass        5:aux:pass      _
5       run     run     VERB    VBN     Tense=Past|VerbForm=Part|Voice=Pass     0       root    0:root  _
6       by      by      ADP     IN      _       8       case    8:case  _
7       the     the     DET     DT      Definite=Def|PronType=Art       8       det     8:det   _
8       head    head    NOUN    NN      Number=Sing     5       obl     5:obl:by        _
9       of      of      ADP     IN      _       12      case    12:case _
10      an      a       DET     DT      Definite=Ind|PronType=Art       12      det     12:det  _
11      investment      investment      NOUN    NN      Number=Sing     12      compound        12:compound     _
12      firm    firm    NOUN    NN      Number=Sing     8       nmod    8:nmod:of       SpaceAfter=No
13      .       .       PUNCT   .       _       5       punct   5:punct _
```

### CODE REVIEW

**Comment by nschneid** [comment]
That's the ordinal rather than fractional use. ADJ is correct (cf. "the third project"). `NumForm=Word` applies to both ordinals and fractions spelled out as words.

**Comment by AngledLuffa** [comment]
> That's the ordinal rather than fractional use. ADJ is correct (cf. "the third project"). `NumForm=Word` applies to any number—cardinal, ordinals, or fractional—spelled out as a word.

Right, the same usage is here for `sixth`

https://github.com/UniversalDependencies/UD_English-EWT/pull/341/commits/d710b99a435cbb8696a792807d44a455ec490fa6

**Comment by nschneid** [comment]
OK good, will merge this and then `NumForm=Word` vs. `NumForm=Combi` can be added later for ordinals.

**Comment by AngledLuffa** [comment]
> OK good, will merge this and then `NumForm=Word` vs. `NumForm=Combi` can be added later for ordinals.

Want me to squash it, or will you?

Also, does the dependency for `sixth` change if we change the POS?

**Comment by nschneid** [comment]
> Also, does the dependency for `sixth` change if we change the POS?

No the ccomp dependency looks correct. At the word level it's ADJ, but it's acting as a fused head of a nominal phrase which is the copular predicate of a subordinate clause.

**Comment by nschneid** [comment]
part of #336

**Pull request merged**
