### PR TITLE
bring sources and generated files into alignment

### PR DESCRIPTION
**Pull request by nschneid**
Combines commits that were made to only the generated files or only the sources

### CODE REVIEW

**Comment by dan-zeman** [comment]
There seem to be 1101 errors instead of previous 1094. Among the new ones are some nasty low-level errors like invalid word id sequence and corrupt tree.

**Comment by nschneid** [comment]
In the validation log I see things like

```
[Line 4072 Sent weblog-juancole.com_juancole_20040708181175_ENG_20040708_181175-0002]: [L1 Format invalid-line] Spurious line: '<<<<<<< HEAD'. All non-empty lines should start with a digit or the # character.
[Line 4074 Sent weblog-juancole.com_juancole_20040708181175_ENG_20040708_181175-0002]: [L1 Format invalid-line] Spurious line: '======='. All non-empty lines should start with a digit or the # character.
[Line 4076 Sent weblog-juancole.com_juancole_20040708181175_ENG_20040708_181175-0002]: [L1 Format invalid-line] Spurious line: '>>>>>>> 6f1c430229855904b172d3cd6b6e3a7509b0b2ba'. All non-empty lines should start with a digit or the # character.
```

which makes it look like markup from a manual merge is in the data, but I can't find it in the train.conllu file!

**Comment by nschneid** [comment]
I did a hard reset of the dev branch in order to remove my earlier commit—maybe that threw the validator off?

**Comment by dan-zeman** [comment]
> I did a hard reset of the dev branch in order to remove my earlier commit—maybe that threw the validator off?

Ah, that is possible. Something similar has happened in another repository before. The validation server automatically pulls from the dev branch whenever it changes. It does not expect git pull to result in a conflict because a conflict can only arise if somebody has fiddled with the git history :-) I will probably have to remove EWT from the validation server and create a new clone there.

**Comment by dan-zeman** [comment]
So the merge conflict has been fixed. From the validation perspective, we are now back at the beginning of the story: there are two error types that were not present in UD 2.6 and the validator is not willing to tolerate them:
```
Unforgivable error 'leaf-mark-case'
Unforgivable error 'rel-upos-cop'
```

**Comment by nschneid** [comment]
Now that the two versions of each tree are in sync I am able to track down the errors. @amir-zeldes could you take a look at #96?

**Pull request merged**
