### PR TITLE
Fix punct edeps

### LINKED ISSUE #453: punct edeprels don't match basic deps
It looks like #449 updated the basic tree only, not the enhanced graph. @martinpopel is there a way to tell the script to do both?

### PR DESCRIPTION
**Pull request by martinpopel**
fixes #453
This is an alternative to #454 (feel free to merge #454 instead of this PR, once it is synced with the current dev; ideally compare this and #454 if there is any diff).

### CODE REVIEW

**Comment by martinpopel** [comment]
I just found out this PR creates three `[L2 Enhanced unconnected-egraph]` validation errors.
I plan to improve the `ud.FixPunct` code to prevent this, but perhaps not today.

**Comment by AngledLuffa** [comment]
Manually fix?

I haven't run the validation on my branch (although the branch is there in the repo for anyone to validate and/or edit)

**Comment by martinpopel** [comment]
This PR is now ready for merge. It passes the validation (except for one warning that was there before my edits).

**Comment by nschneid** [comment]
Thanks!

**Pull request merged**
