### PR TITLE
Commonnouns

### PR DESCRIPTION
**Pull request by jheinecke**
I have changed the UPOS from PROPN to NOUN (and XPOS from NNP(S) to NN(S) of uncapitalised nouns if they are not part of a named entity (#91). This time I made the changes to the files in the `not-to-release/sources` directories. As @nschneid mentioned, I did kept tokens like "americans", or "caucasians" as PROPN.

### CODE REVIEW

**Comment by jheinecke** [comment]
I probably made another error: the commonnouns branch has been made from master not dev ....
If that poses merge problems, I'll delete the commonnouns branch and start again ...

**Comment by dan-zeman** [comment]
> I probably made another error: the commonnouns branch has been made from master not dev ....
> If that poses merge problems, I'll delete the commonnouns branch and start again ...

Besides merge conflicts, it will also copy the eval.log file to the dev branch, but that file is only supposed to be in the master branch, and the validator will report it as an error if it sees it in the dev branch.

**Comment by jheinecke** [comment]
So I better delete the branch commonnoun and report my modifications to a branch derived from dev?

**Comment by dan-zeman** [comment]
> So I better delete the branch commonnoun and report my modifications to a branch derived from dev?

Yes, that will work better, I think.

**Pull request closed without merging**
