### PR TITLE
This one should be a fraction, not a Card

### PR DESCRIPTION
**Pull request by AngledLuffa**
There's also this one, which you mentioned was a tokenization error.  Do anything for the features in the meantime, or just let it be?

### CODE REVIEW

**Comment by nschneid** [comment]
After reading the sentence more carefully I'm not so sure: is "2/3" a date (Feb. 3)? If so the tokenization is correct.

**Comment by nschneid** [comment]
Or is it short for "two of three"? It wouldn't be read as "two thirds", certainly.

**Comment by AngledLuffa** [comment]
I would say 2 out of 3.  Seems kind of awkward to only give one date for
two days of weekend events

**Comment by nschneid** [comment]
Then I would make it three tokens, with "/" as an abbreviation of "of". Do you want me to implement this?

**Comment by AngledLuffa** [comment]
Sure, if you want to do that, I'll ignore this token

**Pull request closed without merging**
