### PR TITLE
fix punctuation

### PR DESCRIPTION
**Pull request by martinpopel**
UD_EWT does not follow [the UD guidelines on punctuation attachment](https://universaldependencies.org/u/dep/punct.html).
This causes many problems such as incompatibility with other English UD trebanks (e.g. GUM follows the guidelines) or users of parsers trained on UD_EWT [complaining about non-projective punct attachments](https://github.com/ufal/udpipe/issues/175#issuecomment-1768050976).

This is my attempt to fix the errors in UD_EWT using [ud.FixPunct](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py).
This PR includes also the script which applies the Udapi block and creates [HTML diff files](https://ufallab.ms.mff.cuni.cz/~popel/ud/ewt-fix-punct/) for easier checking of the edits in this PR.

### CODE REVIEW

**Comment by nschneid** [comment]
Thanks but how is this different from #448?

**Comment by martinpopel** [comment]
Yes, I wanted you to check it and merge it (and I forgot I have push access to this repo).

**Comment by nschneid** [comment]
OK. I already did a git pull locally. What should I do now:

```
$ git pull
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
```

**Comment by AngledLuffa** [comment]
Are there changes you want to keep in your local branch?  If not, you can
always do

git reset --hard origin/dev

if instead you want to keep stuff, it really depends on the context

**Comment by nschneid** [comment]
Thanks that worked. Didn't have any local changes.

**Comment by dan-zeman** [comment]
> OK. I already did a git pull locally. What should I do now:
> 
> ```
> $ git pull
> hint: You have divergent branches and need to specify how to reconcile them.
> hint: You can do so by running one of the following commands sometime before
> hint: your next pull:
> hint:
> hint:   git config pull.rebase false  # merge
> hint:   git config pull.rebase true   # rebase
> hint:   git config pull.ff only       # fast-forward only
> hint:
> hint: You can replace "git config" with "git config --global" to set a default
> hint: preference for all repositories. You can also pass --rebase, --no-rebase,
> hint: or --ff-only on the command line to override the configured default per
> hint: invocation.
> ```

What happened here? Did someone meddle with the commit history? It seems to have knocked down the on-line validation infrastructure (which cannot "always do git reset --hard origin/dev").

**Comment by martinpopel** [comment]
> Did someone meddle with the commit history? 

Yes, I did `git push --force` and I am sorry for the troubles caused. I forgot that the automatic on-line validation will pull each commit even if it is there for just 5 minutes. Now I know I should never force push to UD repos.
(The reason was that I accidentally merged this PR without anyone approving it and I didn't want to spoil the commit history with changes of thousands of files "there, back and there". Now I know it would be the better option.)

**Pull request merged**
